import Footer from '@/src/components/footer/Footer'
import Header from '@/src/components/header/Header'
import Navbar from '@/src/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bonik React Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
